### ISSUE TITLE
SSL?

### ISSUE THREAD

**Issue by Atteli** [LostSoulfly/MinerProxy2#4]
Hi, I'm getting a 

```
[19:00:48 INF] [Rig1] Connecting to eu1.ethermine.org:5555.
[19:00:49 ERR] SendToPool
System.Net.Sockets.SocketException (10053): An established connection was aborted by the software in your host machine
   at System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   at MinerProxy2.Network.Sockets.Client.SendToPool(Byte[] data) in D:\MinerProxy2-master\MinerProxy2\Network\Sockets\Client.cs:line 225
```

when I'm trying to connect to ethermine using port 5555 instead of 4444  (using PhoenixMiner).
Any idea how I can use the SSL port?

**Comment by LostSoulfly** [comment]
SSL is not supported. that's probably why you're seeing this error

**Comment by LostSoulfly** [comment]
I haven't mined in years.. feel free to add SSL support. It doesn't seem like it would be too difficult https://stackoverflow.com/questions/39304612/c-sharp-ssl-tls-with-socket-tcp

**Comment by Atteli** [comment]
Hi, could you please delete this issue? Thanks.
